### ISSUE TITLE
Swift libraries require use_frameworks! which will result in a build error.

### ISSUE THREAD

**Issue by evermeer** [otalk/iOS-demo#10]
When having a project that also has cocoapods written in Swift, it's required to add the use_frameworks! to the pod file like this:

```
platform :ios, '8.0'
use_frameworks!


target "ios-demo" do

pod 'libjingle_peerconnection'
pod 'TLKWebRTC', :git => 'https://github.com/otalk/TLKWebRTC.git'
pod 'TLKSimpleWebRTC', :git => 'https://github.com/otalk/TLKSimpleWebRTC.git'

end
```

When doing that the demo won't build anymore.

It looks like libjingle_peerconnection is not made into a dynamic library... So maybe it's a libjingle_peerconnection issue?

**Comment by evermeer** [comment]
Yes, it looks like it's related to https://github.com/pristineio/webrtc-build-scripts/issues/90

**Comment by evermeer** [comment]
I think the easiest workaround while still using use_frameworks! is:

1. start with a regular 'pod install'
2. Open the Pods folder in finder.
3. Drag the folders libjingle_peerconnection, TLKWebRTC and TLKSimpleWebRTC into your project (iOS-demo in this case) . select copy sources
4 In the podfile comment out the pod 'TLKWebRTC' and 'TLKSimpleWebRTC' and do a 'pod update'
5 Now a compile should work fine.

You do have to do this each time you want to use a new version of  libjingle_peerconnection, TLKWebRTC or TLKSimpleWebRTC

**Comment by mohamedguembri** [comment]
I think you have to modify tyhe PodFile,
try this:


target "ios-demo" do

pod 'libjingle_peerconnection'
pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking'
pod 'TLKWebRTC', :git => 'https://github.com/otalk/TLKWebRTC.git'
pod 'TLKSimpleWebRTC', :git => 'https://github.com/otalk/TLKSimpleWebRTC.git'

end
