### ISSUE TITLE
unaible to see videos on devices

### ISSUE THREAD

**Issue by mohamedguembri** [otalk/iOS-demo#13]
Hi
I can't see any videos on the device (local and remote).
I tested this project with an iPhone5 and an iPad, it looks working perfectly, i can see the stream of my camera on the web, but I can't see it on the device.

**Comment by jfs77** [comment]
it' the same for me... with an iphone 5S ans Ipad 2.

**Comment by mohamedguembri** [comment]
try to separate the local view from the remote view on the storyboard, then you have to make some changes on the viewcontroller.m:

1)add those lines on the viewdidload where you have  NSLog(@"connect success");  :

////////////////////////////////////////////////////////////////////////
RTCVideoTrack * localVideoTrack1 = self.signaling.localMediaStream.videoTracks[0];        
        self.localVideoTrack = localVideoTrack1;
        [self.localVideoTrack addRenderer:self.localView];
 ////////////////////////////////////////////////////////////////////////
   
2)replace the addedStream void with this:
////////////////////////////////////////////////////////////////////////
#pragma mark - TLKSocketIOSignalingDelegate

-(void)socketIOSignaling:(TLKSocketIOSignaling *)socketIOSignaling  addedStream:(TLKMediaStream *)stream {
    NSLog(@"addedStream");
    RTCVideoTrack * remoteVideoTrack = stream.stream.videoTracks[0];
    self.remoteVideoTrack = remoteVideoTrack;
    [self.remoteVideoTrack addRenderer:self.remoteView];
}
////////////////////////////////////////////////////////////////////////
